project:
  name: etl-project
  env: dev

paths:
  base: "./"
  data_raw: "data/raw/"
  data_processed: "data/processed/"

excel:
  engine: "openpyxl"
  header: 0

datasets:
  abastecimientos:
    source:
      folder: "data/raw/abastecimientos/"
      patterns: ["*.xlsx", "*.xlsm"]
      header: 0
      engine: "openpyxl"
    transforms:
      clean_columns: true
      drop_columns:
        - material
        - texto_breve_de_material
        - almacén
        - clase_de_movimiento
        - "posición_doc.mat."
        - "nº_reserva"
        - centro_de_coste
        - "un.medida_de_entrada"
      filters:
        - { column: clase_de_movimiento, op: equals, value: 261}
        - { column: centro_de_coste, op: less_than, value: 20000000}
      rename:
        "fe.contabilización": fecha
        orden: equipo
        "ctd.en_um_entrada": galones
      derive:
        delete_first_n:
          column: equipo
          n: 3
  actividades:
    source:
      folder: "data/raw/actividades/"
      patterns: ["*.xlsx", "*.xlsm"]
      header: 0
      engine: "openpyxl"
    transforms:
      clean_columns: true
      drop_columns:
        - tenencia
        - id
        - nom._empresa
        - parada
        - mov_parada
        - fch_cort_siem
      rename: {}
      filters: []
      derive:
        adjust_date_format:
          column: data
          current_format: "%d/%m/%Y %I:%M:%S %p"
          desired_format: "%d/%m/%Y"
        concat_columns:
          new_column: id
          columns: [fazenda, lote, talhao]
          sep: "_"
          position: 0
  insumos:
    source:
      folder: "data/raw/insumos/"
      patterns: ["*.xlsx", "*.xlsm"]
      header: 0
      engine: "openpyxl"
    transforms:
      clean_columns: true
      drop_columns:
        - tenencia
        - nm_empresa
        - doc_erp
      rename:
        data_apli: fecha
      derive:
        adjust_date_format:
          column: fecha
          current_format: "%d/%m/%Y %I:%M:%S %p"
          desired_format: "%d/%m/%Y"
        concat_column_with_first_n:
          new_column: hda
          column: nm_faz
          n: 3
          position: 0
        concat_columns:
          new_column: id
          columns: [hda, lote, tal]
          sep: "_"
          position: 0
  rep_maquinaria:
    source:
      folder: "data/raw/rep_maquinaria/"
      patterns: ["*.xlsx", "*.xlsm"]
      header: 0
      engine: "openpyxl"
    transforms:
      clean_columns: true
      drop_columns:
        - parada
        - trabajador
        - nombre_operador
        - nombre_de_la_empresa
        - tiporeg
        - nm_parada
      rename:
        equip: equipo
        "hacienda_o.s.": hda
        suerte_apuntamiento: lote
        "suerte_apuntamiento.1": tal
      derive:
        adjust_date_format:
          column: fecha
          current_format: "%d/%m/%Y %I:%M:%S %p"
          desired_format: "%d/%m/%Y"
        concat_columns:
          new_column: id
          columns: [hda, lote, tal]
          sep: "_"
          position: 0