name: ETL

on:
  push:
    branches: [ "main", "pruebas_yaml_2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  etl-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: mydb
        options: >-
          --health-cmd="pg_isready -U myuser -d mydb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSW: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias 
        run: | 
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Ejecutar pipeline transformacion de datos
        run: python scripts/run_all.py

      - name: Ejecutar pipeline carga de datos
        run: python scripts/loadData.py
      
